// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#include "ui.h"

lv_obj_t *uic_balance;
lv_obj_t *uic_Energy;
lv_obj_t *ui_Energy = NULL;lv_obj_t *ui_balance = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Bar2 = NULL;
// event funtions

// build funtions

void ui_Energy_screen_init(void)
{
ui_Energy = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Energy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Energy, lv_color_hex(0x09032E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Energy, lv_color_hex(0x1A2985), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Energy, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Energy, false, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Energy, lv_color_hex(0x040225), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Energy, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Energy, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Energy, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Energy, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Energy, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Energy, lv_color_hex(0xA01515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Energy, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Energy, 182, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Energy, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Energy, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_balance = lv_arc_create(ui_Energy);
lv_obj_set_width( ui_balance, 225);
lv_obj_set_height( ui_balance, 227);
lv_obj_set_align( ui_balance, LV_ALIGN_CENTER );
lv_arc_set_value(ui_balance, 50);
lv_arc_set_mode(ui_balance, LV_ARC_MODE_SYMMETRICAL);
lv_obj_set_style_radius(ui_balance, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_balance, lv_color_hex(0x1261B3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_balance, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_balance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_balance, lv_color_hex(0xEF1616), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_balance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_balance, lv_color_hex(0x40FF6D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_balance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_balance, lv_color_hex(0xA82121), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_balance, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_balance, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_balance, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_balance, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_balance, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_balance, lv_color_hex(0xFF5D40), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_balance, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_Energy);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 150);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

ui_Bar2 = lv_bar_create(ui_Energy);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 150);
lv_obj_set_height( ui_Bar2, 9);
lv_obj_set_x( ui_Bar2, -2 );
lv_obj_set_y( ui_Bar2, 108 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );

uic_Energy = ui_Energy;
uic_balance = ui_balance;

}

void ui_Energy_screen_destroy(void)
{
//  if (ui_Energy) lv_obj_del(ui_Energy);

   // NULL screen variables
   uic_Energy= NULL;
   ui_Energy= NULL;
   uic_balance= NULL;
   ui_balance= NULL;
   ui_Bar1= NULL;
   ui_Bar2= NULL;
}
