// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#include "ui.h"

lv_obj_t *uic_weatherName;
lv_obj_t *uic_Weather;
lv_obj_t *ui_Weather = NULL;lv_obj_t *ui_weatherName = NULL;
// event funtions

// build funtions

void ui_Weather_screen_init(void)
{
ui_Weather = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Weather, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Weather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherName = lv_label_create(ui_Weather);
lv_obj_set_width( ui_weatherName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_weatherName, LV_ALIGN_CENTER );
lv_label_set_text(ui_weatherName,"Weather");
lv_obj_set_style_text_color(ui_weatherName, lv_color_hex(0x2DD227), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_weatherName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_weatherName, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_Weather = ui_Weather;
uic_weatherName = ui_weatherName;

}

void ui_Weather_screen_destroy(void)
{
   if (ui_Weather) lv_obj_del(ui_Weather);

// NULL screen variables
uic_Weather= NULL;
ui_Weather= NULL;
uic_weatherName= NULL;
ui_weatherName= NULL;

}
