// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Clock
extern void ui_Clock_screen_init(void);
extern void ui_Clock_screen_destroy(void);
extern lv_obj_t *ui_Clock;
// CUSTOM VARIABLES
extern lv_obj_t *uic_clock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

