// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#include "../ui.h"

lv_obj_t *uic_Energy;
lv_obj_t *ui_Energy = NULL;lv_obj_t *ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Energy_screen_init(void)
{
ui_Energy = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Energy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Energy, lv_color_hex(0x09032E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Energy, lv_color_hex(0x022225), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Energy, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Energy, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Energy, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Energy, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Energy, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Energy, lv_color_hex(0xA01515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Energy, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Energy, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Energy, 182, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Energy, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Energy, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Energy, lv_color_hex(0xBC2A2A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Energy, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Energy);
lv_img_set_src(ui_Image1, &ui_img_gauge_face_kw_final_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Energy = ui_Energy;

}

void ui_Energy_screen_destroy(void)
{
   if (ui_Energy) lv_obj_del(ui_Energy);

// NULL screen variables
uic_Energy= NULL;
ui_Energy= NULL;
ui_Image1= NULL;

}
