// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Screen1_Label1;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Screen1_Label1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Screen1_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Screen1_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Screen1_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Screen1_Label1, 4 );
lv_obj_set_y( ui_Screen1_Label1, -9 );
lv_obj_set_align( ui_Screen1_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Screen1_Label1,"home");
lv_obj_set_style_text_font(ui_Screen1_Label1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_Screen1_Label1 = ui_Screen1_Label1;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_Screen1_Label1= NULL;
ui_Screen1_Label1= NULL;

}
