#include <lvgl.h>
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_homeName;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Bin1;
extern lv_obj_t *ui_Bin2;
extern lv_obj_t *ui_Bin3;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Home;
extern lv_obj_t *uic_homeName;
extern lv_obj_t *uic_Bin1;
extern lv_obj_t *uic_Bin2;
extern lv_obj_t *uic_Bin3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

