// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#include "ui.h"

lv_obj_t *uic_clock;
lv_obj_t *ui_clock = NULL;lv_obj_t *ui_Label4 = NULL;
// event funtions

// build funtions

void ui_clock_screen_init(void)
{
ui_clock = lv_obj_create(NULL);
lv_obj_clear_flag( ui_clock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_clock);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"00:00:00");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x19BDD8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_clock = ui_clock;

}

void ui_clock_screen_destroy(void)
{
   if (ui_clock) lv_obj_del(ui_clock);

// NULL screen variables
uic_clock= NULL;
ui_clock= NULL;
ui_Label4= NULL;

}
