
#include "../ui.h"
#include <math.h>

// Draw a triangle pointer on the Energy screen based on energy_balance (0-6 mapped to 270 deg arc)
void draw_pointer_for_balance(float energy_balance) {
   if (!ui_Energy) return;
   // Remove any previous pointer (optional: keep a static pointer obj)
   static lv_obj_t *pointer = NULL;
   if (pointer) {
      lv_obj_del(pointer);
      pointer = NULL;
   }
   // Arc parameters
   const int cx = 200, cy = 200, r = 120; // center and radius (adjust as needed)
   // Map energy_balance (0-6) to angle (-135 to 135 deg)
   float angle = -135.0f + (energy_balance / 6.0f) * 270.0f;
   float rad = angle * (M_PI / 180.0f);
   // Pointer triangle base and tip
   int tip_x = cx + (int)(r * cosf(rad));
   int tip_y = cy + (int)(r * sinf(rad));
   int base_left_x = cx + (int)(30 * cosf(rad + M_PI/2));
   int base_left_y = cy + (int)(30 * sinf(rad + M_PI/2));
   int base_right_x = cx + (int)(30 * cosf(rad - M_PI/2));
   int base_right_y = cy + (int)(30 * sinf(rad - M_PI/2));
   // Draw triangle pointer as a canvas
   pointer = lv_canvas_create(ui_Energy);
   static lv_color_t buf[40*40];
   lv_canvas_set_buffer(pointer, buf, 40, 40, LV_IMG_CF_TRUE_COLOR);
   lv_obj_set_pos(pointer, cx-20, cy-20);
   lv_canvas_fill_bg(pointer, lv_color_hex(0x000000), LV_OPA_TRANSP);
   lv_point_t points[3] = {
      {20 + tip_x - cx, 20 + tip_y - cy},
      {20 + base_left_x - cx, 20 + base_left_y - cy},
      {20 + base_right_x - cx, 20 + base_right_y - cy}
   };
   lv_draw_rect_dsc_t dsc;
   lv_draw_rect_dsc_init(&dsc);
   dsc.bg_color = lv_color_hex(0xFF0000);
   dsc.bg_opa = LV_OPA_COVER;
   lv_canvas_draw_polygon(pointer, points, 3, &dsc);
}
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#include "../ui.h"

lv_obj_t *uic_Energy;
lv_obj_t *ui_Energy = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Energy_screen_init(void)
{
ui_Energy = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Energy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Energy, lv_color_hex(0x09032E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Energy, lv_color_hex(0x022225), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Energy, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Energy, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Energy, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Energy, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Energy, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Energy, lv_color_hex(0xA01515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Energy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Energy, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Energy, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Energy, 182, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Energy, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Energy, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Energy, lv_color_hex(0xBC2A2A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Energy, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Energy);
lv_img_set_src(ui_Image2, &ui_img_gauge_face_kw_final_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Energy = ui_Energy;

}

void ui_Energy_screen_destroy(void)
{
   if (ui_Energy) lv_obj_del(ui_Energy);

// NULL screen variables
uic_Energy= NULL;
ui_Energy= NULL;
ui_Image2= NULL;

}
