// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_backImage;
extern lv_obj_t *ui_homeName;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Home;
extern lv_obj_t *uic_backImage;
extern lv_obj_t *uic_homeName;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

