// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Weather
extern void ui_Weather_screen_init(void);
extern void ui_Weather_screen_destroy(void);
extern lv_obj_t *ui_Weather;
extern lv_obj_t *ui_weatherName;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Weather;
extern lv_obj_t *uic_weatherName;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

