// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: clock

#ifndef UI_CLOCKSCREEN_H
#define UI_CLOCKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ClockScreen
extern void ui_ClockScreen_screen_init(void);
extern void ui_ClockScreen_screen_destroy(void);
extern lv_obj_t *ui_ClockScreen;
extern lv_obj_t *ui_time;
// CUSTOM VARIABLES
extern lv_obj_t *uic_time;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

