// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#ifndef UI_ENERGY_H
#define UI_ENERGY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Energy
extern void ui_Energy_screen_init(void);
extern void ui_Energy_screen_destroy(void);
extern lv_obj_t *ui_Energy;
extern lv_obj_t *ui_balance;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Checkbox1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Energy;
extern lv_obj_t *uic_balance;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

