// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#include "../ui.h"

lv_obj_t *uic_Settings;
lv_obj_t *ui_Settings = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Switch1 = NULL;
// event funtions

// build funtions

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x5FA3E8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Settings);
lv_obj_set_width( ui_Panel1, 300);
lv_obj_set_height( ui_Panel1, 300);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xCB1111), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Panel1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch1 = lv_switch_create(ui_Settings);
lv_obj_set_width( ui_Switch1, 83);
lv_obj_set_height( ui_Switch1, 29);
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );

uic_Settings = ui_Settings;

}

void ui_Settings_screen_destroy(void)
{
   if (ui_Settings) lv_obj_del(ui_Settings);

// NULL screen variables
uic_Settings= NULL;
ui_Settings= NULL;
ui_Panel1= NULL;
ui_Switch1= NULL;

}
