// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: knob

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Switch1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Settings;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

